---

- name: Update and Upgrade centos
  hosts: centos7mirrors
  tasks:

  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: install openldap-servers
    yum:
      name: openldap-servers
      state: latest

  - name: install openldap-clients
    yum:
      name: openldap-clients
      state: latest

  - name: deploy DB_CONFIG
    copy:
      src: /srv/DB_CONFIG
      dest: /var/lib/ldap/DB_CONFIG
      owner: ldap
      group: ldap
      mode: '0644'

  - name: start slapd
    systemd:
      state: started
      name: slapd

  - name: enable slapd
    systemd:
      enabled: yes
      name: slapd

  - name: deploy chrootpw.ldif
    copy:
      src: /srv/chrootpw.ldif
      dest: /root/chrootpw.ldif
      owner: root
      group: root
      mode: '0644'

  - name: deploy chdomain.ldif
    copy:
      src: /srv/chdomain.ldif
      dest: /root/chdomain.ldif
      owner: root
      group: root
      mode: '0644'

  - name: deploy basedomain.ldif
    copy:
      src: /srv/basedomain.ldif
      dest: /root/basedomain.ldif
      owner: root
      group: root
      mode: '0644'

  - name: deploy mod_syncprov.ldif
    copy:
      src: /srv/mod_syncprov.ldif
      dest: /root/mod_syncprov.ldif
      owner: root
      group: root
      mode: '0644'

  - name: deploy syncprov.ldif
    copy:
      src: /srv/syncprov.ldif
      dest: /root/syncprov.ldif
      owner: root
      group: root
      mode: '0644'

  - name: set firewalld to allow ldap
    shell: firewall-cmd --add-service=ldap --permanent
    args:
      executable: /bin/bash


- name: set the first master 01
  hosts: master01
  tasks:

  - name: deploy set-mirror1.ldif
    copy:
      src: /srv/set-mirror1.ldif
      dest: /root/set-mirror1.ldif
      owner: root
      group: root
      mode: '0644'

- name: set the second master 02
  hosts: master02
  tasks:

  - name: deploy set-mirror2.ldif
    copy:
      src: /srv/set-mirror2.ldif
      dest: /root/set-mirror2.ldif
      owner: root
      group: root
      mode: '0644'

- name: set the second master 03
  hosts: master03
  tasks:

  - name: deploy set-mirror3.ldif
    copy:
      src: /srv/set-mirror3.ldif
      dest: /root/set-mirror3.ldif
      owner: root
      group: root
      mode: '0644'

- name: set the second master 04
  hosts: master04
  tasks:

  - name: deploy set-mirror4.ldif
    copy:
      src: /srv/set-mirror4.ldif
      dest: /root/set-mirror4.ldif
      owner: root
      group: root
      mode: '0644'

...
